// import { Square, Cat, Dog, Leaf } from 'lucide-react';

export const themes = {
    default: {
        id: 'default',
        label: 'Oscuro',
        icon: 'square',
        bg: "bg-gradient-to-br from-indigo-900 via-purple-900 to-black text-white",
        header: "bg-black/90 border-white/20 shadow-xl",
        headerText: "text-white",
        card: "bg-white/10 border-white/20 hover:bg-white/15 text-gray-200 shadow-lg",
        cardTitle: "text-white font-semibold",
        highlight: "text-blue-400",
        titleGradient: "from-blue-400 to-purple-500",
        buttonPrimary: "bg-blue-600 hover:bg-blue-500 text-white shadow-md hover:shadow-lg active:scale-95 transition-all font-extrabold",
        buttonSecondary: "bg-white/20 hover:bg-white/30 text-white border border-white/10 shadow-sm hover:shadow-md active:scale-95 transition-all font-extrabold",
        input: "bg-black/40 border-white/20 text-white placeholder-white/40 shadow-inner",
        player: "bg-black/60 border-white/20 shadow-2xl",
        progressColor: "bg-blue-400",
        iconColor: "text-blue-400",
        ringColor: "ring-blue-500",
        activeBg: "bg-white/30",
        iconFill: "fill-current"
    },
    kitten: {
        id: 'kitten',
        label: 'Gatitos',
        icon: 'cat',
        bg: "bg-gradient-to-br from-pink-100 via-rose-100 to-red-100 text-rose-950",
        header: "bg-white/90 border-pink-300 shadow-md",
        headerText: "text-rose-900 font-extrabold",
        card: "bg-white/80 border-pink-200 hover:bg-white/100 text-rose-900 shadow-md hover:shadow-xl transition-all",
        cardTitle: "text-rose-800 font-bold",
        highlight: "text-pink-600",
        titleGradient: "from-pink-500 to-rose-600",
        buttonPrimary: "bg-pink-500 hover:bg-pink-400 text-white shadow-md hover:shadow-lg active:scale-95 transition-all font-extrabold",
        buttonSecondary: "bg-rose-200 hover:bg-rose-300 text-rose-900 border border-rose-300 shadow-sm hover:shadow-md active:scale-95 transition-all font-extrabold",
        input: "bg-white/70 border-pink-300 text-rose-900 shadow-inner",
        player: "bg-white/90 border-pink-200 shadow-2xl",
        progressColor: "bg-pink-500",
        iconColor: "text-pink-500",
        ringColor: "ring-pink-400",
        activeBg: "bg-pink-200",
        iconFill: "fill-none",
        customIcon: "/kitten-fan.png",
        backgroundImage: "/kitten-fan.png",
        bgRepeat: true
    },
    puppy: {
        id: 'puppy',
        label: 'Cowboy',
        icon: 'dog',
        bg: "bg-gradient-to-br from-amber-100 via-orange-100 to-stone-200 text-stone-900",
        header: "bg-white/90 border-amber-300 shadow-md",
        headerText: "text-stone-900 font-extrabold",
        card: "bg-white/80 border-amber-200 hover:bg-white/100 text-stone-800 shadow-md hover:shadow-xl transition-all",
        cardTitle: "text-stone-900 font-bold",
        highlight: "text-amber-700",
        titleGradient: "from-amber-600 to-orange-700",
        buttonPrimary: "bg-amber-600 hover:bg-amber-500 text-white shadow-md hover:shadow-lg active:scale-95 transition-all font-extrabold",
        buttonSecondary: "bg-amber-200 hover:bg-amber-300 text-stone-900 border border-amber-300 shadow-sm hover:shadow-md active:scale-95 transition-all font-extrabold",
        input: "bg-white/70 border-amber-300 text-stone-900 shadow-inner",
        player: "bg-white/90 border-amber-200 shadow-2xl",
        progressColor: "bg-amber-500",
        iconColor: "text-amber-600",
        ringColor: "ring-amber-500",
        activeBg: "bg-amber-300",
        iconFill: "fill-none",
        customIcon: "/kitten-cowboy.png",
        backgroundImage: "/kitten-cowboy.png",
        bgRepeat: true
    },
    nature: {
        id: 'nature',
        label: 'Naturaleza',
        icon: 'leaf',
        bg: "bg-gradient-to-br from-emerald-50 via-green-100 to-teal-50 text-emerald-950", 
        header: "bg-emerald-900/10 border-emerald-400 shadow-md backdrop-blur-lg",
        headerText: "text-emerald-950 font-extrabold",
        card: "bg-white/80 border-emerald-300 hover:bg-white/100 text-emerald-900 shadow-md hover:shadow-xl transition-all",
        cardTitle: "text-emerald-950 font-bold",
        highlight: "text-emerald-800",
        titleGradient: "from-emerald-700 to-green-800",
        buttonPrimary: "bg-emerald-700 hover:bg-emerald-600 text-white shadow-md hover:shadow-lg active:scale-95 transition-all font-extrabold",
        buttonSecondary: "bg-emerald-200 hover:bg-emerald-300 text-emerald-950 border border-emerald-300 shadow-sm hover:shadow-md active:scale-95 transition-all font-extrabold",
        input: "bg-white/70 border-emerald-300 text-emerald-950 shadow-inner",
        player: "bg-white/80 border-emerald-200 shadow-2xl",
        progressColor: "bg-emerald-700",
        iconColor: "text-emerald-800",
        ringColor: "ring-emerald-600",
        activeBg: "bg-emerald-300",
        iconFill: "fill-none"
    }
};
